-- Add up migration script here
ALTER TABLE sites
ADD COLUMN enable INTEGER NOT NULL DEFAULT 1;

ALTER TABLE pages
ADD COLUMN enable INTEGER NOT NULL DEFAULT 1;

ALTER TABLE rules
ADD COLUMN enable INTEGER NOT NULL DEFAULT 1;

ALTER TABLE downloads
ADD COLUMN enable INTEGER NOT NULL DEFAULT 1;
